<?xml version="1.0"?>
<package format="3">
  <name>go2_behaviors</name>
  <version>0.1.0</version>
  <description>基于 ros2_control 标准关节轨迹接口的 Go2 仿真动作。</description>
  <maintainer email="hao@example.com">hao</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>builtin_interfaces</exec_depend>
  <exec_depend>control_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
